= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/syslog-ng-formula/compare/v0.5.0...v0.5.1++[0.5.1^] (2020-09-09)

=== Bug Fixes

* *libtofs:* “files_switch” mess up the variable exported by “map.jinja”
 [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/e9c515371b39015d3606e9668663c207d6758f9e[e9c5153^])
* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/4d6851dd78c532a012cb3fd983a9d49077605c37[4d6851d^])
* *state:* restart service when configuration has changed
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/a8100d0f325c8f8f792b6b9c9e342cf63e13ab3d[a8100d0^])

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/b44bfb5872050352cca6fe0d139da5b640764515[b44bfb5^])
* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/4af7a0fdd620ff6128493a2222dcf752234b078f[4af7a0f^])
* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/b44b24ed5c5064003ae9c45056b836e186b5ab81[b44b24e^])
* *kitchen:* install required packages to bootstrapped `opensuse` [skip
ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/8fe499e72225ef4b0493d4fabde4188b4d08b66b[8fe499e^])
* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/3ce84e4cf0ec254b3a28cb850465da883f871725[3ce84e4^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/68366d70525cc184351a7d054ee36dd4fb2fc7a6[68366d7^])
* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/17620541caf56056e294301e88c85fa151cb7174[1762054^])
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2` [skip
ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/9b435f2b6081bff0e127006392cf420279a60ceb[9b435f2^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/766962a6b020e1061c1b6e3cdc91cd4e7fa41dc7[766962a^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/b5ebab04471f9501b58eaaf9efc7f89b18bdd5c7[b5ebab0^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/7cffd70d4812b65ca23a6abdea9a01f5ce710ec1[7cffd70^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/c3685b356d01ac5f033e10c0669587b443a3f3cf[c3685b3^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/3d5cd5ccf3183d6305cf3acebaea1183630b438e[3d5cd5c^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/668926cbd8ccf7e15ee7a95641dac5aac0285782[668926c^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/fd9aba207ee8f041ad3b9f36a33a03160c555518[fd9aba2^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/ce2de8b669d7792d416eab477279a8f7a8b157f7[ce2de8b^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/dcfa3d5c7de1c815667f4bbcb0f79de5c0ddab6e[dcfa3d5^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/9d34a6399fcebba85ce7901e37349cb518b098b5[9d34a63^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/ff23c72345c244748226931fd8067e9877563b60[ff23c72^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/a3fd56e002f2013c08b94ec86b66c980ac0f6812[a3fd56e^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/2eb11ff146bcf05b8082bfc1e312f1a464743f69[2eb11ff^])

=== Documentation

* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/b44429d6c43f9ab6a149ceb6b0c223d8d1af340b[b44429d^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/9231f3f1443d8da399299abdb414a5704590d101[9231f3f^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/19586109fa38eaa709a06cdcbb5fef83b4cd4ad5[1958610^])

=== Styles

* *libtofs.jinja:* use Black-inspired Jinja formatting [skip ci]
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/3de8cb74624825cc4f8ecc05fbc76b29f39f736c[3de8cb7^])

== link:++https://github.com/saltstack-formulas/syslog-ng-formula/compare/v0.4.0...v0.5.0++[0.5.0^] (2019-10-01)

=== Bug Fixes

* *pillar:* rearrange `tofs` block to avoid `yamllint` error
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/7c4dd84[7c4dd84^])

=== Features

* *tofs:* add TOFS support
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/6a6f255[6a6f255^])

== link:++https://github.com/saltstack-formulas/syslog-ng-formula/compare/v0.3.0...v0.4.0++[0.4.0^] (2019-09-30)

=== Bug Fixes

* *syslog_ng.sls:* fix `yamllint` errors in test pillar
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/8f6c57f[8f6c57f^]),
closes
https://github.com//travis-ci.com/saltstack-formulas/syslog-ng-formula/builds/129135816/issues/L210-L217[/travis-ci.com/saltstack-formulas/syslog-ng-formula/builds/129135816#L210-L217^]

=== Code Refactoring

* *pillars:* dry default pillars
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/2f169e2[2f169e2^])
* *states:* switch to the new directory layout
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/7ea12e3[7ea12e3^])

=== Continuous Integration

* use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/9151f4e[9151f4e^])
* *cirrus:* update test matrix
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/7e3826b[7e3826b^])
* *kitchen:* change `log_level` to `debug` instead of `info`
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/8c7b3f0[8c7b3f0^])
* *kitchen+travis:* replace EOL pre-salted images
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/25f12ac[25f12ac^])
* *travis:* fix CentOS instance name
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/2a94fab[2a94fab^])
* *travis:* test formula with Travis
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/2049866[2049866^])
* *yamllint:* add rule `empty-values` & use new `yaml-files` setting
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/abd2920[abd2920^])

=== Features

* *distro:* add support for CentOS
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/7311f10[7311f10^])
* *distro:* add support for OpenSuse
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/3258ee0[3258ee0^])
* *install:* provide EPEL repo configuration for `Amazon Linux-2`
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/4e46ea0[4e46ea0^])
* *pillar:* update map.jinja from template-formula
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/c027735[c027735^])
* *platform:* add support for `Arch`
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/2112711[2112711^])

=== Tests

* *inspec:* fix test on syslog-ng.conf file
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/bd2506f[bd2506f^])
* *pillar:* use custom pillar file to run tests
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/5cb5bd4[5cb5bd4^])
* *refactor:* split tests (config/package/service)
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/b7fac62[b7fac62^])

== link:++https://github.com/saltstack-formulas/syslog-ng-formula/compare/v0.2.2...v0.3.0++[0.3.0^] (2019-08-17)

=== Continuous Integration

* *cirrus:* use cirrus-ci alongisde travis-ci
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/51271b6[51271b6^])
* *kitchen+travis:* modify matrix to include `develop` platform
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/b47b992[b47b992^])

=== Features

* *yamllint:* include for this repo and apply rules throughout
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/a81ae52[a81ae52^])

== link:++https://github.com/saltstack-formulas/syslog-ng-formula/compare/v0.2.1...v0.2.2++[0.2.2^] (2019-05-26)

=== Documentation

* *readme:* add testing requirements section
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/06de318[06de318^])

== link:++https://github.com/saltstack-formulas/syslog-ng-formula/compare/v0.2.0...v0.2.1++[0.2.1^] (2019-05-26)

=== Bug Fixes

* *inspec:* move test suite to test/integration/default
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/0ba5fce[0ba5fce^])
* *inspec:* update Inspec profile definition
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/85bdfbb[85bdfbb^])

=== Continuous Integration

* *kitchen:* rename Kitchen config file
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/dcbc58d[dcbc58d^])
* *kitchen+travis:* test with more distros
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/b1acda9[b1acda9^])
* *travis:* debian wheezy is no longer supported
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/e6d2a06[e6d2a06^])

=== Documentation

* *readme:* fix typos, update README with testing info
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/35d0ca4[35d0ca4^])
* *readme:* update readme
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/0193e22[0193e22^])
* *semantic-release:* implement an automated changelog
(https://github.com/saltstack-formulas/syslog-ng-formula/commit/98e17dd[98e17dd^])
